export const CREATE_USER_START = "CREATE_USER_START"
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS" 
export const CREATE_USER_FAILED = "CREATE_USER_FAILED"

export const GET_USER_START = "GET_USER_START"
export const GET_USER_SUCCESS = "GET_USER_SUCCESS"
export const GET_USER_FAILED = "GET_USER_FAILED" 

export const EDIT_USER_START = "EDIT_USER_START"
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS"
export const EDIT_USER_FAILED = "EDIT_USER_FAILED"

export const DELETE_USER_START = "DELETE_USER_START"
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"
export const DELETE_USER_FAILED  = "DELETE_USER_FAILED"

export const FETCH_USERS_START = "FETCH_USERS_START"
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS"
export const FETCH_USERS_FAILED = "FETCH_USERS_FAILED" 

